[package]
name = "swap"
version = "0.1.0"
authors = ["Nicotinas <rhino879@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
