[package]
name = "swap"
version = "0.1.0"
authors = ["Shivin01 <shivin.agarwal15@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
